name: Different Mind Build

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.19'
      - name: Run Build
        run: |
          chmod +x ./go-build-all.sh
          ./go-build-all.sh
          ls -lah ./build/
      - uses: actions/upload-artifact@v4
        with:
          path: ./build/*
