name: Different Mind Build

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15'
      - name: Download packr2
        run: go get -u github.com/gobuffalo/packr/v2/packr2
      - name: Run packr2
        run: |
          packr2
          sed -i 's#github/workspace#mc8051.de/SerialLogger/v1#g' main-packr.go
          sed -i 's#home/runner/work/serial-logger/serial-logger#mc8051.de/SerialLogger/v1#g' main-packr.go
          cat main-packr.go
      - name: Run Build
        run: |
          chmod +x ./go-build-all.sh
          ./go-build-all.sh
          ls -lah ./build/
      - uses: actions/upload-artifact@v2
        with:
          path: ./build/*