name: Different Mind Build

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      - name: Run Build
        run: |
          chmod +x ./go-build-all.sh
          ./go-build-all.sh
          ls -lah ./build/
      - uses: actions/upload-artifact@v3
        with:
          path: ./build/*